spring.application.name=demo

spring.datasource.url=${DB_URL}
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform= org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

# jwt configuration
todolistdb.jwt.secretKey=${JWT_SECRET}
todolistdb.jwt.validity=7
todolistdb.jwt.authHeader=Authorization
todolistdb.jwt.prefix=Bearer

### Paths
todolistdb.security.paths.endpoints.public=/api/v1/idm/login,/error,/api/v1/idm/register,/api/v1/idm/forget,/api/v1/idm/verifyOtp,/api/v1/idm/update-password,/v3/api-docs/**,/swagger-ui/**,/api-doc/**
todolistdb.security.paths.actuator.public=/actuator/health,/actuator/info
todolistdb.security.paths.actuator.private=/actuator/**

logging.level.org.springframework.boot.autoconfigure.liquibase=DEBUG
logging.level.liquibase=INFO